### PR TITLE
Debounce scroll handler for smoother UI.

### PR DESCRIPTION
**Pull request by michaelballantyne**
Scrolling a long ways down the page with the live view open currently jitters badly as the live view is updated before I stop scrolling. This change debounces the scroll handler so that an update only occurs when scrolling has stopped.

### CODE REVIEW

**Comment by michaelballantyne** [comment]
(Note that I didn't run the build to update the `dist` files, as it isn't clear to me how to do so.)

**Comment by felixhayashi** [comment]
Hi @michaelballantyne 

thanks for contributing

apologies, I actually forgot to push the updated hotzone code which is included at tiddlymap.org to this repo. So I now updated the code, could you please add your changes to the new code I just pushed to this repo so I can test it?

> Scrolling a long ways down the page with the live view open currently jitters badly as the live view is updated before I stop scrolling.

That is actually intentional so the live view updates itself while the user is scrolling. From my experience, the jitter may also result from css3 effects (if you have any enabled).

Anyhow, I think your argument also makes sense so I'll make it optional whether the hotzone trigger is delayed or not with your debounce function.

-felix

**Comment by michaelballantyne** [comment]
> Could you please add your changes to the new code I just pushed to this repo so I can test it?

Done!

> That is actually intentional so the live view updates itself while the user is scrolling.

I'd be with you if it weren't for the lag on re-draw. As it is the updates during scroll make it pretty much unusable in my wiki. The TiddlyMap.com wiki is mostly OK, but still not as smooth as it should be.

> From my experience, the jitter may also result from css3 effects (if you have any enabled).

I'm using the standard Snow White theme without modification, and running under Chrome. Is there anything in there I should look out for?

It's possible that the live view re-draw performance is more of a problem for me just because of number of tiddlers. I've got ~1000 vs ~200 on TiddlyMap.com. (This might also point to a performance bottleneck in TiddlyMap's on change handler?)

> I'll make it optional whether the hotzone trigger is delayed or not with your debounce function.

Give it a try with my modifications first? I find it provides a much smoother experience, and the live view re-draw on scroll normally can't keep up anyway, so it isn't much missed. It'd be a shame to bloat the options unnecessarily.

**Comment by felixhayashi** [comment]
Yeah, I like it. Thanks for your contribution :)

-felix

**Pull request merged**
